apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "citus.fullname" . }}-coordinator
spec:
  serviceName: {{ include "citus.fullname" . }}-coordinator
  replicas: {{ .Values.replicaCount.coordinator }}
  selector:
    matchLabels:
      app: {{ include "citus.fullname" . }}-coordinator
  template:
    metadata:
      labels:
        app: {{ include "citus.fullname" . }}-coordinator
    spec:
      containers:
      - name: citus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresPassword | quote }}
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
