apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus.fullname" . }}-worker
  labels:
    app: {{ include "citus.fullname" . }}-worker
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: {{ include "citus.fullname" . }}-worker
